// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: checkpoint/v1beta/msg.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCheckpoint defines a message to crete checkpoint.
type MsgCheckpoint struct {
	Proposer        string `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	StartBlock      uint64 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock        uint64 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	RootHash        string `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	AccountRootHash string `protobuf:"bytes,5,opt,name=account_root_hash,json=accountRootHash,proto3" json:"account_root_hash,omitempty"`
	BorChainID      string `protobuf:"bytes,6,opt,name=bor_chainID,json=borChainID,proto3" json:"bor_chainID,omitempty"`
}

func (m *MsgCheckpoint) Reset()         { *m = MsgCheckpoint{} }
func (m *MsgCheckpoint) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpoint) ProtoMessage()    {}
func (*MsgCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{0}
}
func (m *MsgCheckpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpoint.Merge(m, src)
}
func (m *MsgCheckpoint) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpoint proto.InternalMessageInfo

// MsgValidatorJoinResponse defines ValidatorJoin response type.
type MsgCheckpointResponse struct {
}

func (m *MsgCheckpointResponse) Reset()         { *m = MsgCheckpointResponse{} }
func (m *MsgCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpointResponse) ProtoMessage()    {}
func (*MsgCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{1}
}
func (m *MsgCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpointResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpointResponse.Merge(m, src)
}
func (m *MsgCheckpointResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpointResponse proto.InternalMessageInfo

// MsgCheckpoint defines a message to checkpoint ack.
type MsgCheckpointAck struct {
	From       string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Number     uint64 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Proposer   string `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	StartBlock uint64 `protobuf:"varint,4,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock   uint64 `protobuf:"varint,5,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	RootHash   string `protobuf:"bytes,6,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	TxHash     string `protobuf:"bytes,7,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LogIndex   uint64 `protobuf:"varint,8,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
}

func (m *MsgCheckpointAck) Reset()         { *m = MsgCheckpointAck{} }
func (m *MsgCheckpointAck) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpointAck) ProtoMessage()    {}
func (*MsgCheckpointAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{2}
}
func (m *MsgCheckpointAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpointAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpointAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpointAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpointAck.Merge(m, src)
}
func (m *MsgCheckpointAck) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpointAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpointAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpointAck proto.InternalMessageInfo

// MsgCheckpointAckResponse defines CheckpointAck response type.
type MsgCheckpointAckResponse struct {
}

func (m *MsgCheckpointAckResponse) Reset()         { *m = MsgCheckpointAckResponse{} }
func (m *MsgCheckpointAckResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpointAckResponse) ProtoMessage()    {}
func (*MsgCheckpointAckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{3}
}
func (m *MsgCheckpointAckResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpointAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpointAckResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpointAckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpointAckResponse.Merge(m, src)
}
func (m *MsgCheckpointAckResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpointAckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpointAckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpointAckResponse proto.InternalMessageInfo

// MsgCheckpoint defines a message to checkpoint no ack.
type MsgCheckpointNoAck struct {
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
}

func (m *MsgCheckpointNoAck) Reset()         { *m = MsgCheckpointNoAck{} }
func (m *MsgCheckpointNoAck) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpointNoAck) ProtoMessage()    {}
func (*MsgCheckpointNoAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{4}
}
func (m *MsgCheckpointNoAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpointNoAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpointNoAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpointNoAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpointNoAck.Merge(m, src)
}
func (m *MsgCheckpointNoAck) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpointNoAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpointNoAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpointNoAck proto.InternalMessageInfo

// MsgCheckpointNoAckResponse defines CheckpointNoAck response type.
type MsgCheckpointNoAckResponse struct {
}

func (m *MsgCheckpointNoAckResponse) Reset()         { *m = MsgCheckpointNoAckResponse{} }
func (m *MsgCheckpointNoAckResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCheckpointNoAckResponse) ProtoMessage()    {}
func (*MsgCheckpointNoAckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f8314581ee9560, []int{5}
}
func (m *MsgCheckpointNoAckResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCheckpointNoAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCheckpointNoAckResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCheckpointNoAckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCheckpointNoAckResponse.Merge(m, src)
}
func (m *MsgCheckpointNoAckResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCheckpointNoAckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCheckpointNoAckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCheckpointNoAckResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCheckpoint)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpoint")
	proto.RegisterType((*MsgCheckpointResponse)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpointResponse")
	proto.RegisterType((*MsgCheckpointAck)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpointAck")
	proto.RegisterType((*MsgCheckpointAckResponse)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpointAckResponse")
	proto.RegisterType((*MsgCheckpointNoAck)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpointNoAck")
	proto.RegisterType((*MsgCheckpointNoAckResponse)(nil), "heimdall.checkpoint.v1beta1.MsgCheckpointNoAckResponse")
}

func init() { proto.RegisterFile("checkpoint/v1beta/msg.proto", fileDescriptor_54f8314581ee9560) }

var fileDescriptor_54f8314581ee9560 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x26, 0x4d, 0x93, 0xa9, 0xaa, 0xc2, 0x0a, 0xa8, 0xe5, 0x20, 0xa7, 0xca, 0xa9,
	0xaa, 0x84, 0xad, 0xa6, 0x42, 0x48, 0xdc, 0xda, 0x72, 0xa0, 0x87, 0x70, 0xc8, 0x91, 0x8b, 0x65,
	0x6f, 0x16, 0xdb, 0xf2, 0x9f, 0xb1, 0x76, 0x37, 0x10, 0xc4, 0x0b, 0x70, 0xe4, 0x11, 0xfa, 0x38,
	0x1c, 0x7b, 0xe4, 0x82, 0x84, 0x92, 0x03, 0xbc, 0x00, 0x77, 0x94, 0xf5, 0x9f, 0xc6, 0x41, 0x8d,
	0xd2, 0x9b, 0x77, 0xbe, 0xdf, 0x7c, 0xa3, 0xf9, 0xbc, 0x5a, 0xe8, 0xd1, 0x80, 0xd1, 0x28, 0xc3,
	0x30, 0x95, 0xf6, 0xc7, 0x33, 0x8f, 0x49, 0xd7, 0x4e, 0x84, 0x6f, 0x65, 0x1c, 0x25, 0x92, 0x5e,
	0xc0, 0xc2, 0x64, 0xe2, 0xc6, 0xb1, 0x75, 0x47, 0x59, 0x39, 0x75, 0x66, 0x3c, 0xf1, 0xd1, 0x47,
	0xc5, 0xd9, 0xcb, 0xaf, 0xbc, 0x65, 0xf0, 0x53, 0x83, 0x83, 0x91, 0xf0, 0xaf, 0x2a, 0x9e, 0x18,
	0xd0, 0xc9, 0x38, 0x66, 0x28, 0x18, 0xd7, 0xb5, 0x63, 0xed, 0xa4, 0x3b, 0xae, 0xce, 0xa4, 0x0f,
	0xfb, 0x42, 0xba, 0x5c, 0x3a, 0x5e, 0x8c, 0x34, 0xd2, 0x77, 0x8e, 0xb5, 0x93, 0xd6, 0x18, 0x54,
	0xe9, 0x72, 0x59, 0x21, 0x3d, 0xe8, 0xb2, 0x74, 0x52, 0xc8, 0x4d, 0x25, 0x77, 0x58, 0x3a, 0xa9,
	0x44, 0x8e, 0x28, 0x9d, 0xc0, 0x15, 0x81, 0xde, 0xca, 0xad, 0x97, 0x85, 0xb7, 0xae, 0x08, 0xc8,
	0x29, 0x3c, 0x76, 0x29, 0xc5, 0x69, 0x2a, 0x9d, 0x3b, 0x68, 0x57, 0x41, 0x87, 0x85, 0x30, 0x2e,
	0xd9, 0x3e, 0xec, 0x7b, 0xc8, 0x1d, 0x1a, 0xb8, 0x61, 0x7a, 0xfd, 0x46, 0x6f, 0x2b, 0x0a, 0x3c,
	0xe4, 0x57, 0x79, 0xe5, 0x75, 0xe7, 0xeb, 0x4d, 0xbf, 0xf1, 0xe7, 0xa6, 0xdf, 0x18, 0x1c, 0xc1,
	0xd3, 0xda, 0x7a, 0x63, 0x26, 0x32, 0x4c, 0x05, 0x1b, 0xfc, 0xd5, 0xe0, 0x51, 0x4d, 0xb9, 0xa0,
	0x11, 0x21, 0xd0, 0xfa, 0xc0, 0x31, 0x29, 0xf6, 0x56, 0xdf, 0xe4, 0x19, 0xb4, 0xd3, 0x69, 0xe2,
	0x31, 0x5e, 0xac, 0x5b, 0x9c, 0x6a, 0x39, 0x35, 0x37, 0xe7, 0xd4, 0xda, 0x9c, 0xd3, 0xee, 0xa6,
	0x9c, 0xda, 0x6b, 0x39, 0x1d, 0xc1, 0x9e, 0x9c, 0xe5, 0xd2, 0x9e, 0x92, 0xda, 0x72, 0xa6, 0x84,
	0x1e, 0x74, 0x63, 0xf4, 0x9d, 0x30, 0x9d, 0xb0, 0x99, 0xde, 0xc9, 0x2d, 0x63, 0xf4, 0xaf, 0x97,
	0xe7, 0x95, 0x40, 0x0c, 0xd0, 0xd7, 0xd7, 0xae, 0x32, 0x19, 0x02, 0xa9, 0x69, 0xef, 0xf0, 0x9e,
	0x50, 0x56, 0xfc, 0x9e, 0x83, 0xf1, 0x7f, 0x4f, 0xe9, 0x38, 0xfc, 0xbd, 0x03, 0xcd, 0x91, 0xf0,
	0x49, 0x0c, 0xb0, 0x72, 0xc5, 0x4e, 0xad, 0x0d, 0x17, 0xd5, 0xaa, 0xd9, 0x19, 0xc3, 0xed, 0xd9,
	0x72, 0x2a, 0x99, 0xc2, 0x41, 0xfd, 0xbf, 0xbe, 0xd8, 0xde, 0xe4, 0x82, 0x46, 0xc6, 0xcb, 0x07,
	0xe1, 0xd5, 0xd8, 0x2f, 0x70, 0xb8, 0x9e, 0x9d, 0xbd, 0xbd, 0x93, 0x6a, 0x30, 0x5e, 0x3d, 0xb0,
	0xa1, 0x1c, 0x7e, 0x39, 0xfa, 0x3e, 0x37, 0xb5, 0xdb, 0xb9, 0xa9, 0xfd, 0x9a, 0x9b, 0xda, 0xb7,
	0x85, 0xd9, 0xb8, 0x5d, 0x98, 0x8d, 0x1f, 0x0b, 0xb3, 0xf1, 0xfe, 0xdc, 0x0f, 0x65, 0x30, 0xf5,
	0x2c, 0x8a, 0x89, 0x9d, 0xb8, 0x32, 0xa4, 0x29, 0x93, 0x9f, 0x90, 0x47, 0x76, 0x39, 0xc9, 0x9e,
	0xd9, 0x2b, 0xaf, 0x8a, 0xfc, 0x9c, 0x31, 0xe1, 0xb5, 0xd5, 0xf3, 0x70, 0xfe, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x44, 0xa8, 0x6b, 0xab, 0x70, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Checkpoint defines Checkpoint.
	Checkpoint(ctx context.Context, in *MsgCheckpoint, opts ...grpc.CallOption) (*MsgCheckpointResponse, error)
	// CheckpointAck defines ack to checkpoint
	CheckpointAck(ctx context.Context, in *MsgCheckpointAck, opts ...grpc.CallOption) (*MsgCheckpointAckResponse, error)
	// CheckpointNoAck defines no ack to checkpoint
	CheckpointNoAck(ctx context.Context, in *MsgCheckpointNoAck, opts ...grpc.CallOption) (*MsgCheckpointNoAckResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Checkpoint(ctx context.Context, in *MsgCheckpoint, opts ...grpc.CallOption) (*MsgCheckpointResponse, error) {
	out := new(MsgCheckpointResponse)
	err := c.cc.Invoke(ctx, "/heimdall.checkpoint.v1beta1.Msg/Checkpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CheckpointAck(ctx context.Context, in *MsgCheckpointAck, opts ...grpc.CallOption) (*MsgCheckpointAckResponse, error) {
	out := new(MsgCheckpointAckResponse)
	err := c.cc.Invoke(ctx, "/heimdall.checkpoint.v1beta1.Msg/CheckpointAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CheckpointNoAck(ctx context.Context, in *MsgCheckpointNoAck, opts ...grpc.CallOption) (*MsgCheckpointNoAckResponse, error) {
	out := new(MsgCheckpointNoAckResponse)
	err := c.cc.Invoke(ctx, "/heimdall.checkpoint.v1beta1.Msg/CheckpointNoAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Checkpoint defines Checkpoint.
	Checkpoint(context.Context, *MsgCheckpoint) (*MsgCheckpointResponse, error)
	// CheckpointAck defines ack to checkpoint
	CheckpointAck(context.Context, *MsgCheckpointAck) (*MsgCheckpointAckResponse, error)
	// CheckpointNoAck defines no ack to checkpoint
	CheckpointNoAck(context.Context, *MsgCheckpointNoAck) (*MsgCheckpointNoAckResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Checkpoint(ctx context.Context, req *MsgCheckpoint) (*MsgCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (*UnimplementedMsgServer) CheckpointAck(ctx context.Context, req *MsgCheckpointAck) (*MsgCheckpointAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckpointAck not implemented")
}
func (*UnimplementedMsgServer) CheckpointNoAck(ctx context.Context, req *MsgCheckpointNoAck) (*MsgCheckpointNoAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckpointNoAck not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCheckpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdall.checkpoint.v1beta1.Msg/Checkpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Checkpoint(ctx, req.(*MsgCheckpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CheckpointAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCheckpointAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CheckpointAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdall.checkpoint.v1beta1.Msg/CheckpointAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CheckpointAck(ctx, req.(*MsgCheckpointAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CheckpointNoAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCheckpointNoAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CheckpointNoAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdall.checkpoint.v1beta1.Msg/CheckpointNoAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CheckpointNoAck(ctx, req.(*MsgCheckpointNoAck))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "heimdall.checkpoint.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkpoint",
			Handler:    _Msg_Checkpoint_Handler,
		},
		{
			MethodName: "CheckpointAck",
			Handler:    _Msg_CheckpointAck_Handler,
		},
		{
			MethodName: "CheckpointNoAck",
			Handler:    _Msg_CheckpointNoAck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkpoint/v1beta/msg.proto",
}

func (m *MsgCheckpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BorChainID) > 0 {
		i -= len(m.BorChainID)
		copy(dAtA[i:], m.BorChainID)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.BorChainID)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AccountRootHash) > 0 {
		i -= len(m.AccountRootHash)
		copy(dAtA[i:], m.AccountRootHash)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.AccountRootHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.EndBlock != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlock != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCheckpointResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpointResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpointResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCheckpointAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpointAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpointAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LogIndex != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.LogIndex))
		i--
		dAtA[i] = 0x40
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.EndBlock != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x28
	}
	if m.StartBlock != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Number != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCheckpointAckResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpointAckResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpointAckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCheckpointNoAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpointNoAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpointNoAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCheckpointNoAckResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCheckpointNoAckResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCheckpointNoAckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCheckpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.StartBlock != 0 {
		n += 1 + sovMsg(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovMsg(uint64(m.EndBlock))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.AccountRootHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.BorChainID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *MsgCheckpointResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCheckpointAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.Number != 0 {
		n += 1 + sovMsg(uint64(m.Number))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.StartBlock != 0 {
		n += 1 + sovMsg(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovMsg(uint64(m.EndBlock))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.LogIndex != 0 {
		n += 1 + sovMsg(uint64(m.LogIndex))
	}
	return n
}

func (m *MsgCheckpointAckResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCheckpointNoAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *MsgCheckpointNoAckResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCheckpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRootHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountRootHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BorChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCheckpointResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpointResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpointResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCheckpointAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpointAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpointAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCheckpointAckResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpointAckResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpointAckResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCheckpointNoAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpointNoAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpointNoAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCheckpointNoAckResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCheckpointNoAckResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCheckpointNoAckResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsg = fmt.Errorf("proto: unexpected end of group")
)
