defaultStake: 10000
defaultFee: 2000
borChainId: 15001
heimdallChainId: heimdall-15001
contractsBranch: mardizzone/node-16
genesisContractsBranch: master
sprintSize:
  - '64'
blockNumber:
  - '0'
blockTime:
  - '2'
numOfBorValidators: 3
numOfBorSentries: 0
numOfBorArchiveNodes: 0
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#develop"
heimdallDockerBuildContext: "../../heimdall"
sprintSizeBlockNumber:
  - '0'
devnetBorFlags: config,config,config
