// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: topup/v1beta/msg.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_maticnetwork_heimdall_types_common "github.com/maticnetwork/heimdall/types/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the topup module's genesis state.
type MsgTopup struct {
	FromAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"from_address,omitempty"`
	User        github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=user,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"user,omitempty"`
	// TODO Sandeep: check if uint64 can be casted to int or something else has
	// to be done
	Fee         github_com_cosmos_cosmos_sdk_types.Int                     `protobuf:"varint,3,opt,name=fee,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Int" json:"fee,omitempty"`
	TxHash      github_com_maticnetwork_heimdall_types_common.HeimdallHash `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3,casttype=github.com/maticnetwork/heimdall/types/common.HeimdallHash" json:"tx_hash,omitempty"`
	LogIndex    uint64                                                     `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	BlockNumber uint64                                                     `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
}

func (m *MsgTopup) Reset()         { *m = MsgTopup{} }
func (m *MsgTopup) String() string { return proto.CompactTextString(m) }
func (*MsgTopup) ProtoMessage()    {}
func (*MsgTopup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d59e70ac70f1c423, []int{0}
}
func (m *MsgTopup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTopup.Unmarshal(m, b)
}
func (m *MsgTopup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTopup.Marshal(b, m, deterministic)
}
func (m *MsgTopup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTopup.Merge(m, src)
}
func (m *MsgTopup) XXX_Size() int {
	return xxx_messageInfo_MsgTopup.Size(m)
}
func (m *MsgTopup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTopup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTopup proto.InternalMessageInfo

func (m *MsgTopup) GetFromAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgTopup) GetUser() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MsgTopup) GetFee() github_com_cosmos_cosmos_sdk_types.Int {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *MsgTopup) GetTxHash() github_com_maticnetwork_heimdall_types_common.HeimdallHash {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *MsgTopup) GetLogIndex() uint64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *MsgTopup) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type MsgTopupResponse struct {
}

func (m *MsgTopupResponse) Reset()         { *m = MsgTopupResponse{} }
func (m *MsgTopupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTopupResponse) ProtoMessage()    {}
func (*MsgTopupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d59e70ac70f1c423, []int{1}
}
func (m *MsgTopupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTopupResponse.Unmarshal(m, b)
}
func (m *MsgTopupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTopupResponse.Marshal(b, m, deterministic)
}
func (m *MsgTopupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTopupResponse.Merge(m, src)
}
func (m *MsgTopupResponse) XXX_Size() int {
	return xxx_messageInfo_MsgTopupResponse.Size(m)
}
func (m *MsgTopupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTopupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTopupResponse proto.InternalMessageInfo

type MsgWithdrawFee struct {
	UserAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"user_address,omitempty"`
	// TODO Sandeep: check if uint64 can be casted to int or something else has
	// to be done
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"varint,2,opt,name=amount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount,omitempty"`
}

func (m *MsgWithdrawFee) Reset()         { *m = MsgWithdrawFee{} }
func (m *MsgWithdrawFee) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFee) ProtoMessage()    {}
func (*MsgWithdrawFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_d59e70ac70f1c423, []int{2}
}
func (m *MsgWithdrawFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdrawFee.Unmarshal(m, b)
}
func (m *MsgWithdrawFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdrawFee.Marshal(b, m, deterministic)
}
func (m *MsgWithdrawFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFee.Merge(m, src)
}
func (m *MsgWithdrawFee) XXX_Size() int {
	return xxx_messageInfo_MsgWithdrawFee.Size(m)
}
func (m *MsgWithdrawFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFee.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFee proto.InternalMessageInfo

func (m *MsgWithdrawFee) GetUserAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *MsgWithdrawFee) GetAmount() github_com_cosmos_cosmos_sdk_types.Int {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgWithdrawFeeResponse struct {
}

func (m *MsgWithdrawFeeResponse) Reset()         { *m = MsgWithdrawFeeResponse{} }
func (m *MsgWithdrawFeeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFeeResponse) ProtoMessage()    {}
func (*MsgWithdrawFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d59e70ac70f1c423, []int{3}
}
func (m *MsgWithdrawFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdrawFeeResponse.Unmarshal(m, b)
}
func (m *MsgWithdrawFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdrawFeeResponse.Marshal(b, m, deterministic)
}
func (m *MsgWithdrawFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFeeResponse.Merge(m, src)
}
func (m *MsgWithdrawFeeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgWithdrawFeeResponse.Size(m)
}
func (m *MsgWithdrawFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFeeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTopup)(nil), "heimdall.topup.v1beta1.MsgTopup")
	proto.RegisterType((*MsgTopupResponse)(nil), "heimdall.topup.v1beta1.MsgTopupResponse")
	proto.RegisterType((*MsgWithdrawFee)(nil), "heimdall.topup.v1beta1.MsgWithdrawFee")
	proto.RegisterType((*MsgWithdrawFeeResponse)(nil), "heimdall.topup.v1beta1.MsgWithdrawFeeResponse")
}

func init() { proto.RegisterFile("topup/v1beta/msg.proto", fileDescriptor_d59e70ac70f1c423) }

var fileDescriptor_d59e70ac70f1c423 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x4e, 0xb6, 0xdd, 0xba, 0x3b, 0x5d, 0x44, 0x06, 0x29, 0xa1, 0x42, 0x5a, 0x7b, 0x58, 0x8a,
	0xb0, 0x13, 0xaa, 0x37, 0x11, 0x61, 0x0b, 0x4a, 0xf7, 0x50, 0x0f, 0x71, 0x61, 0xc1, 0x4b, 0x99,
	0x24, 0xb3, 0x93, 0xd0, 0x4c, 0x5e, 0xc8, 0x4c, 0xdc, 0xfa, 0x2f, 0xfc, 0x1d, 0xfe, 0x0b, 0x6f,
	0x1e, 0xf7, 0xe8, 0xa9, 0x48, 0xfb, 0x2f, 0x7a, 0x10, 0x99, 0x49, 0x03, 0x15, 0xc4, 0xad, 0xb2,
	0xa7, 0xc9, 0xbc, 0x7c, 0xdf, 0x97, 0x97, 0xef, 0x7b, 0x0f, 0x75, 0x14, 0xe4, 0x65, 0xee, 0x7d,
	0x1c, 0x05, 0x4c, 0x51, 0x4f, 0x48, 0x4e, 0xf2, 0x02, 0x14, 0xe0, 0x4e, 0xcc, 0x12, 0x11, 0xd1,
	0x34, 0x25, 0x06, 0x40, 0x2a, 0xc0, 0xa8, 0xfb, 0x98, 0x03, 0x07, 0x03, 0xf1, 0xf4, 0x53, 0x85,
	0x1e, 0xfc, 0x3c, 0x40, 0x47, 0x53, 0xc9, 0x2f, 0x35, 0x14, 0x5f, 0xa2, 0x93, 0xeb, 0x02, 0xc4,
	0x8c, 0x46, 0x51, 0xc1, 0xa4, 0x74, 0xec, 0xbe, 0x3d, 0x3c, 0x1e, 0x8f, 0x36, 0xcb, 0xde, 0x19,
	0x4f, 0x54, 0x5c, 0x06, 0x24, 0x04, 0xe1, 0x85, 0x20, 0x05, 0xc8, 0xed, 0x71, 0x26, 0xa3, 0xb9,
	0xa7, 0x3e, 0xe5, 0x4c, 0x92, 0xf3, 0x30, 0x3c, 0xaf, 0x88, 0x7e, 0x5b, 0xcb, 0x6c, 0x2f, 0xf8,
	0x0d, 0x6a, 0x96, 0x92, 0x15, 0xce, 0xc1, 0xff, 0xaa, 0x19, 0x3a, 0x7e, 0x85, 0x1a, 0xd7, 0x8c,
	0x39, 0x8d, 0xbe, 0x3d, 0x6c, 0x8e, 0x9f, 0x6d, 0x96, 0xbd, 0xd3, 0x3d, 0x54, 0x2e, 0x32, 0xe5,
	0x6b, 0x1a, 0xbe, 0x42, 0x0f, 0xd4, 0x62, 0x16, 0x53, 0x19, 0x3b, 0x4d, 0xd3, 0xc7, 0xeb, 0xcd,
	0xb2, 0xf7, 0x72, 0x47, 0x41, 0x50, 0x95, 0x84, 0x19, 0x53, 0x37, 0x50, 0xcc, 0xbd, 0xda, 0xc2,
	0x4a, 0xc5, 0x0b, 0x41, 0x08, 0xc8, 0xc8, 0x64, 0x5b, 0x9d, 0x50, 0x19, 0xfb, 0x2d, 0xb5, 0xd0,
	0x27, 0x7e, 0x82, 0x8e, 0x53, 0xe0, 0xb3, 0x24, 0x8b, 0xd8, 0xc2, 0x39, 0xd4, 0xcd, 0xf9, 0x47,
	0x29, 0xf0, 0x0b, 0x7d, 0xc7, 0x4f, 0xd1, 0x49, 0x90, 0x42, 0x38, 0x9f, 0x65, 0xa5, 0x08, 0x58,
	0xe1, 0xb4, 0xcc, 0xfb, 0xb6, 0xa9, 0xbd, 0x33, 0xa5, 0x01, 0x46, 0x8f, 0x6a, 0xff, 0x7d, 0x26,
	0x73, 0xc8, 0x24, 0x1b, 0x7c, 0xb1, 0xd1, 0xc3, 0xa9, 0xe4, 0x57, 0x89, 0x8a, 0xa3, 0x82, 0xde,
	0xbc, 0x65, 0x4c, 0x47, 0xa3, 0x5d, 0xb8, 0x87, 0x68, 0xb4, 0x4c, 0x1d, 0xcd, 0x18, 0xb5, 0xa8,
	0x80, 0x32, 0x53, 0x26, 0x9c, 0x7f, 0xb3, 0x75, 0xcb, 0x1c, 0x38, 0xa8, 0xf3, 0x7b, 0xaf, 0xf5,
	0x6f, 0x3c, 0xff, 0x6a, 0xa3, 0xc6, 0x54, 0x72, 0xfc, 0x1e, 0x1d, 0x56, 0xf3, 0xd5, 0x27, 0x7f,
	0x9e, 0x4d, 0x52, 0x3b, 0xd0, 0x1d, 0xde, 0x85, 0xa8, 0xc5, 0x31, 0x43, 0xed, 0x5d, 0x7f, 0x4e,
	0xff, 0x42, 0xdc, 0xc1, 0x75, 0xc9, 0x7e, 0xb8, 0xfa, 0x33, 0xe3, 0xc9, 0xb7, 0x95, 0x6b, 0xdd,
	0xae, 0x5c, 0xeb, 0xc7, 0xca, 0xb5, 0x3e, 0xaf, 0x5d, 0xeb, 0x76, 0xed, 0x5a, 0xdf, 0xd7, 0xae,
	0xf5, 0x81, 0xdc, 0x39, 0x3c, 0x0b, 0xaf, 0x5a, 0x51, 0xe3, 0x59, 0xd0, 0x32, 0x0b, 0xf7, 0xe2,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0x39, 0x90, 0x5c, 0xb8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Topup defines a method to topup validator account with additional tokens.
	Topup(ctx context.Context, in *MsgTopup, opts ...grpc.CallOption) (*MsgTopupResponse, error)
	// WithdrawFee defines a method for validators to withdraw tokens from
	// heimdall.
	WithdrawFee(ctx context.Context, in *MsgWithdrawFee, opts ...grpc.CallOption) (*MsgWithdrawFeeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Topup(ctx context.Context, in *MsgTopup, opts ...grpc.CallOption) (*MsgTopupResponse, error) {
	out := new(MsgTopupResponse)
	err := c.cc.Invoke(ctx, "/heimdall.topup.v1beta1.Msg/Topup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawFee(ctx context.Context, in *MsgWithdrawFee, opts ...grpc.CallOption) (*MsgWithdrawFeeResponse, error) {
	out := new(MsgWithdrawFeeResponse)
	err := c.cc.Invoke(ctx, "/heimdall.topup.v1beta1.Msg/WithdrawFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Topup defines a method to topup validator account with additional tokens.
	Topup(context.Context, *MsgTopup) (*MsgTopupResponse, error)
	// WithdrawFee defines a method for validators to withdraw tokens from
	// heimdall.
	WithdrawFee(context.Context, *MsgWithdrawFee) (*MsgWithdrawFeeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Topup(ctx context.Context, req *MsgTopup) (*MsgTopupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Topup not implemented")
}
func (*UnimplementedMsgServer) WithdrawFee(ctx context.Context, req *MsgWithdrawFee) (*MsgWithdrawFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFee not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Topup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTopup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Topup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdall.topup.v1beta1.Msg/Topup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Topup(ctx, req.(*MsgTopup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdall.topup.v1beta1.Msg/WithdrawFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawFee(ctx, req.(*MsgWithdrawFee))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "heimdall.topup.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Topup",
			Handler:    _Msg_Topup_Handler,
		},
		{
			MethodName: "WithdrawFee",
			Handler:    _Msg_WithdrawFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topup/v1beta/msg.proto",
}
