FROM alpine:3.14

RUN set -x \
    && apk add --update --no-cache \
       ca-certificates \
    && rm -rf /var/cache/apk/*

COPY heimdalld /usr/local/bin/
COPY bridge /usr/local/bin/
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh

EXPOSE 1317 26656 26657

ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/entrypoint.sh"]
