#!/bin/bash
#
#
##################
# Stops existing for upgrade
export HEIMDALL_DIR=/var/lib/heimdall
sudo -u heimdall heimdalld init --chain={{NETWORK}} --home /var/lib/heimdall
sudo chown -R heimdall $HEIMDALL_DIR
#################
#sudo systemctl stop heimdalld.service
