name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo "running build"
        docker build -f Dockerfile.deprecated -t maticnetwork/heimdall:${GITHUB_REF/refs\/tags\//} .
        echo "pushing image"
        docker push maticnetwork/heimdall:${GITHUB_REF/refs\/tags\//}
        echo "DONE!"
